max_timestep: 6000
agent_count: 100
neighbourhood_size: 10
color_count: 5
majority_color_ratio: 0.7
informed_ratio: 1.0
personal_info_weight: 0.0
sensor_noise: 0.0
communication_noise: 0.0
color_change_timestep: 1000
total_simulation_runs: 40